export const SELECT_ARTICLE = "SELECT_ARTICLE";
export const GET_ARTICLE_LIST_REQUEST = "GET_ARTICLE_LIST_REQUEST";
export const SET_ARTICLE_LIST = "SET_ARTICLE_LIST";
export const SET_SELECTED_LABEL = "SET_SELECTED_LABEL";